# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BASE_VERSION=15

FROM ghcr.io/daemonless/base:${BASE_VERSION}

WORKDIR /app

ARG FREEBSD_ARCH=amd64
ARG APP_VERSION=latest

LABEL org.opencontainers.image.title="Bulwark Webmail" \
      org.opencontainers.image.description="Bulwark Webmail on FreeBSD." \
      org.opencontainers.image.source="https://github.com/bulwarkmail/webmail" \
      org.opencontainers.image.url="https://bulwarkmail.org/" \
      org.opencontainers.image.licenses="AGPL-3.0" \
      org.opencontainers.image.vendor="daemonless" \
      io.daemonless.category="Communication" \
      io.daemonless.port="3000" \
      io.daemonless.arch="${FREEBSD_ARCH}"

RUN pkg update && \
    pkg install -y node ca_root_nss && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/* && \
    pw groupadd -n nodejs -g 1001 || true && \
    pw useradd -n nextjs -u 1001 -g nodejs -d /app -s /usr/sbin/nologin || true

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

COPY bulwark-standalone/ ./
COPY bulwark-static/ ./.next/static
COPY bulwark-public/ ./public

COPY root/ /

RUN mkdir -p /app/data /config && \
    chown -R nextjs:nodejs /app /config && \
    chmod +x /etc/services.d/bulwark-webmail-dbuild/run /healthz 2>/dev/null || true && \
    echo "${APP_VERSION}" > /app/version

USER nextjs

EXPOSE 3000

VOLUME /app/data

CMD ["node", "server.js"]